version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/management
    volumes:
      - .:/app
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
    networks:
      - app-network

  db:
    image: mysql:8
    env_file:
      - docker/db-mysql/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/db-mysql/conf.d:/etc/mysql/conf.d
      - ./docker/db-mysql/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
